/**
 * Per-repo schema EXTRACTOR SCRIPTS: generation, storage, execution.
 *
 * Instead of shipping a parser per stack, each repo gets its own extractor
 * written by a Claude Code agent that reads the actual codebase. The agent's
 * job is narrow and fixed: emit a script that prints the repo's DECLARED schema
 * as JSON in the contract below. Everything downstream — diagram, diff — only
 * ever sees that contract, so any stack works as long as its script does.
 *
 * Scripts live in the board's data dir (`<dataDir>/schema-scripts/<repoId>.sh`),
 * keyed by project repo, so every task on that repo shares one script and no
 * user repository is polluted.
 *
 * The script is generated by an agent and then EXECUTED locally, which is the
 * design the feature asks for. Two guards keep that honest: generation runs the
 * agent with read-only tools, and the script's output is fully validated here —
 * a malformed or hostile payload yields warnings and dropped entries, never
 * unchecked data downstream.
 */
import { execFile } from "node:child_process";
import fs from "node:fs/promises";
import path from "node:path";
import { promisify } from "node:util";

import type {
  SchemaEntity,
  SchemaField,
  SchemaGraph,
  SchemaRelation,
} from "../../shared/types.js";

const execFileAsync = promisify(execFile);

/** How long a generated extractor may run before being killed. */
const RUN_TIMEOUT_MS = 30_000;
/**
 * How long the generating agent may take. Generous on purpose: it reads a whole
 * codebase and tests its own script, and it runs as a background job, so a slow
 * repo costs patience rather than a failed request.
 */
const GENERATE_TIMEOUT_MS = 30 * 60_000;
/** Cap on a script's stdout. */
const MAX_OUTPUT_BYTES = 32 * 1024 * 1024;
/** Defensive caps on what a script may declare. */
const MAX_ENTITIES = 2000;
const MAX_FIELDS_PER_ENTITY = 500;
const MAX_RELATIONS = 5000;

/** Result of parsing a script's output. */
export interface ExtractResult {
  entities: SchemaEntity[];
  relations: SchemaRelation[];
  /** Non-fatal problems found while validating the payload. */
  warnings: string[];
  /** Free-form dialect label the script reported (e.g. "rails", "prisma"). */
  dialect: string;
}

/** Raised when a script cannot be run or its output cannot be trusted. */
export class SchemaScriptError extends Error {
  constructor(message: string) {
    super(message);
    this.name = "SchemaScriptError";
  }
}

/* ────────────────────────────────────────────────────────────────────────
 * Storage
 * ──────────────────────────────────────────────────────────────────────── */

/** Where a project repo's extractor lives. */
export function scriptPathFor(dataDir: string, projectRepoId: string): string {
  return path.join(dataDir, "schema-scripts", `${safeId(projectRepoId)}.sh`);
}

/** Sidecar holding when the script was generated and what it detected. */
export function metaPathFor(dataDir: string, projectRepoId: string): string {
  return path.join(dataDir, "schema-scripts", `${safeId(projectRepoId)}.json`);
}

/** Ids come from the database, but never interpolate one into a path raw. */
const safeId = (id: string): string => id.replace(/[^A-Za-z0-9_-]/g, "_");

export interface ScriptMeta {
  generatedAt: string;
  /** The agent's one-line description of what it found. */
  summary: string;
}

export async function readMeta(
  dataDir: string,
  projectRepoId: string,
): Promise<ScriptMeta | null> {
  try {
    const raw = await fs.readFile(metaPathFor(dataDir, projectRepoId), "utf8");
    const parsed: unknown = JSON.parse(raw);
    if (!isRecord(parsed)) return null;
    return {
      generatedAt: String(parsed.generatedAt ?? ""),
      summary: String(parsed.summary ?? ""),
    };
  } catch {
    return null;
  }
}

export async function scriptExists(
  dataDir: string,
  projectRepoId: string,
): Promise<boolean> {
  try {
    await fs.access(scriptPathFor(dataDir, projectRepoId));
    return true;
  } catch {
    return false;
  }
}

/* ────────────────────────────────────────────────────────────────────────
 * Execution
 * ──────────────────────────────────────────────────────────────────────── */

/**
 * Run an extractor with `cwd` as the repo root and validate what it prints.
 * Throws {@link SchemaScriptError} when the script fails, times out, or emits
 * something that is not the contract.
 */
export async function runScript(
  scriptPath: string,
  cwd: string,
): Promise<ExtractResult> {
  let stdout: string;
  try {
    const res = await execFileAsync("bash", [scriptPath], {
      cwd,
      timeout: RUN_TIMEOUT_MS,
      maxBuffer: MAX_OUTPUT_BYTES,
      env: { ...process.env, CK_SCHEMA_REPO: cwd },
    });
    stdout = res.stdout;
  } catch (err) {
    const e = err as NodeJS.ErrnoException & { stderr?: string; killed?: boolean };
    if (e.killed) {
      throw new SchemaScriptError(
        `El script tardó más de ${RUN_TIMEOUT_MS / 1000}s y fue interrumpido.`,
      );
    }
    const detail = (e.stderr ?? e.message ?? "").trim().split("\n").slice(-4).join(" ");
    throw new SchemaScriptError(`El script falló: ${detail || "sin salida"}`);
  }
  return parseScriptOutput(stdout);
}

/**
 * Validate a script's stdout against the contract. Everything is checked and
 * coerced: unknown shapes are dropped with a warning rather than trusted, so a
 * bad generation degrades to a partial diagram instead of corrupt data.
 */
export function parseScriptOutput(stdout: string): ExtractResult {
  const warnings: string[] = [];
  const payload = extractJson(stdout);

  const rawEntities = Array.isArray(payload.entities) ? payload.entities : [];
  const rawRelations = Array.isArray(payload.relations) ? payload.relations : [];
  if (!Array.isArray(payload.entities)) {
    warnings.push("La salida no traía un array `entities`.");
  }

  const entities = parseEntities(rawEntities, warnings);
  // Las relaciones se validan CONTRA las tablas que sobrevivieron arriba, no
  // contra las que el script dijo tener: una FK a una tabla descartada apunta
  // a la nada igual que una a una tabla inexistente.
  const declared = new Set(entities.map((e) => e.name));
  const relations = parseRelations(rawRelations, declared, warnings);

  if (entities.length === 0) {
    throw new SchemaScriptError(
      "El script no declaró ninguna tabla. Revisá el script generado o volvé a generarlo.",
    );
  }

  return {
    entities,
    relations,
    warnings,
    dialect: asString(payload.dialect) ?? "generado",
  };
}

/** Coerce the declared tables, dropping the nameless and the duplicated. */
function parseEntities(raw: unknown[], warnings: string[]): SchemaEntity[] {
  if (raw.length > MAX_ENTITIES) {
    warnings.push(`Se ignoraron tablas por encima de ${MAX_ENTITIES}.`);
  }

  const entities: SchemaEntity[] = [];
  const seen = new Set<string>();
  for (const entity of raw.slice(0, MAX_ENTITIES)) {
    if (!isRecord(entity) || typeof entity.name !== "string" || entity.name.length === 0) {
      warnings.push("Se descartó una tabla sin nombre.");
      continue;
    }
    if (seen.has(entity.name)) {
      warnings.push(`Tabla duplicada: ${entity.name}.`);
      continue;
    }
    seen.add(entity.name);
    entities.push({
      name: entity.name,
      fields: parseFields(entity.fields, entity.name, warnings),
      sourceFile: asString(entity.sourceFile) ?? "",
      sourceLine: asPositiveInt(entity.sourceLine) ?? 0,
      pending: entity.pending === true,
    });
  }
  return entities;
}

/** Coerce the declared foreign keys, dropping the ones with no real endpoints. */
function parseRelations(
  raw: unknown[],
  declared: Set<string>,
  warnings: string[],
): SchemaRelation[] {
  const relations: SchemaRelation[] = [];
  for (const relation of raw.slice(0, MAX_RELATIONS)) {
    if (
      !isRecord(relation) ||
      typeof relation.from !== "string" ||
      typeof relation.to !== "string" ||
      relation.from.length === 0 ||
      relation.to.length === 0
    ) {
      warnings.push("Se descartó una relación sin extremos.");
      continue;
    }
    // A relation to a table that was never declared would render as a phantom
    // box in the diagram, so it is dropped rather than drawn.
    if (!declared.has(relation.from) || !declared.has(relation.to)) {
      warnings.push(
        `Relación ignorada por apuntar a una tabla inexistente: ${relation.from} → ${relation.to}.`,
      );
      continue;
    }
    relations.push({
      from: relation.from,
      to: relation.to,
      fromField: asString(relation.fromField) ?? "",
      onDelete: asString(relation.onDelete),
      sourceFile: asString(relation.sourceFile) ?? "",
      sourceLine: asPositiveInt(relation.sourceLine) ?? 0,
      pending: relation.pending === true,
    });
  }
  return relations;
}

function parseFields(
  raw: unknown,
  entityName: string,
  warnings: string[],
): SchemaField[] {
  if (!Array.isArray(raw)) return [];
  const fields: SchemaField[] = [];
  for (const f of raw.slice(0, MAX_FIELDS_PER_ENTITY)) {
    if (!isRecord(f) || typeof f.name !== "string" || f.name.length === 0) {
      warnings.push(`Columna sin nombre en ${entityName}.`);
      continue;
    }
    const field: SchemaField = {
      name: f.name,
      type: asString(f.type) ?? "",
      // Absent nullability reads as nullable, the laxer of the two.
      nullable: f.nullable !== false,
      primaryKey: f.primaryKey === true,
      pending: f.pending === true,
    };
    const def = asString(f.default);
    if (def !== null) field.default = def;
    fields.push(field);
  }
  return fields;
}

/**
 * Pull the JSON object out of a script's stdout. Pure JSON is expected, but a
 * script that also logs to stdout is common enough to be worth surviving, so
 * the outermost braces are used as a fallback.
 */
function extractJson(stdout: string): Record<string, unknown> {
  const trimmed = stdout.trim();
  if (trimmed.length === 0) {
    throw new SchemaScriptError("El script no imprimió nada.");
  }

  const attempt = (text: string): Record<string, unknown> | null => {
    try {
      const parsed: unknown = JSON.parse(text);
      return isRecord(parsed) ? parsed : null;
    } catch {
      return null;
    }
  };

  const direct = attempt(trimmed);
  if (direct) return direct;

  const start = trimmed.indexOf("{");
  const end = trimmed.lastIndexOf("}");
  if (start !== -1 && end > start) {
    const sliced = attempt(trimmed.slice(start, end + 1));
    if (sliced) return sliced;
  }

  throw new SchemaScriptError(
    `La salida del script no es JSON válido: ${trimmed.slice(0, 200)}`,
  );
}

/* ────────────────────────────────────────────────────────────────────────
 * Generation
 * ──────────────────────────────────────────────────────────────────────── */

/** The contract the generated script must satisfy, as told to the agent. */
export const SCRIPT_CONTRACT = `{
  "dialect": "rails",
  "entities": [
    {
      "name": "posts",
      "sourceFile": "db/schema.rb",
      "sourceLine": 42,
      "fields": [
        { "name": "id", "type": "bigint", "nullable": false, "primaryKey": true },
        { "name": "user_id", "type": "bigint", "nullable": false },
        { "name": "title", "type": "string", "nullable": true, "default": "''" }
      ]
    }
  ],
  "relations": [
    {
      "from": "posts",
      "fromField": "user_id",
      "to": "users",
      "onDelete": "cascade",
      "sourceFile": "db/schema.rb",
      "sourceLine": 120
    }
  ]
}`;

/** Prompt handed to the generating agent. */
export function buildGenerationPrompt(repoName: string): string {
  return `Escribí un script de extracción de esquema para este repositorio (${repoName}).

CONTEXTO
Una herramienta va a ejecutar tu script para dibujar un diagrama entidad-relación
del esquema que este proyecto DECLARA EN SU CÓDIGO. El objetivo es ver la
estructura que describen los archivos (modelos de ORM, migraciones, schema.sql,
schema.prisma, models.py, entidades, etc.), NO los datos de una base corriendo.

TAREA
1. Explorá el repositorio y descubrí dónde está declarado el esquema. Puede ser
   cualquier stack. Si hay varias fuentes, elegí la más completa y autoritativa
   (por ejemplo un schema consolidado antes que migraciones sueltas), y
   considerá también las migraciones/archivos que todavía no estén reflejados
   ahí.
2. Escribí un script que imprima ese esquema como JSON en stdout.

REQUISITOS DEL SCRIPT
- Se ejecuta con \`bash <script>\` desde la RAÍZ del repositorio (cwd = raíz).
- Solo LEE archivos. No se conecta a ninguna base de datos, no usa la red, no
  escribe ni modifica nada, y no ejecuta comandos del proyecto que puedan tener
  efectos (nada de migrar, instalar dependencias ni levantar servidores).
- Termina en menos de 20 segundos.
- Usa solo herramientas que ya estén disponibles en el sistema. Podés escribirlo
  en bash, o embeber python3/node si el parseo lo amerita — pero verificá que el
  intérprete que elijas exista antes de depender de él.
- Imprime EXCLUSIVAMENTE el JSON en stdout (los mensajes de diagnóstico van a
  stderr). Si algo falla, terminá con código distinto de cero y el motivo en
  stderr.
- Tiene que ser robusto: si un archivo no existe, que no reviente.

CONTRATO DE SALIDA (exacto)
${SCRIPT_CONTRACT}

Reglas del contrato:
- "entities": una por tabla/modelo. "name" es obligatorio y único.
- "fields": columnas declaradas. "nullable" y "primaryKey" son booleanos;
  "default" es opcional.
- "relations": UNA POR CADA foreign key declarada, con la DIRECCIÓN correcta:
  "from" es la entidad HIJA (la que tiene la clave foránea) y "to" es la entidad
  PADRE a la que apunta. "fromField" es la columna que guarda la referencia.
  Esta dirección es lo más importante del diagrama: no la inviertas.
  Solo relaciones con foreign key real: una asociación que el esquema no declara
  como tal (por ejemplo una polimórfica \`<algo>_type\` + \`<algo>_id\`, que por
  definición no puede tener foreign key) NO se emite. El diagrama muestra lo que
  la base declara, no lo que el código infiere.
- "from" y "to" deben coincidir exactamente con un "name" de "entities"; las
  relaciones que apunten a entidades no declaradas se descartan.
- "sourceFile" (ruta relativa a la raíz del repo) y "sourceLine" permiten saltar
  a la declaración: completalos siempre que puedas.
- "dialect": etiqueta corta del stack detectado (por ejemplo "rails", "prisma",
  "django", "sql").

VERIFICACIÓN OBLIGATORIA antes de responder
Ejecutá el script y comprobá que: imprime JSON válido, la cantidad de entidades
coincide con las tablas realmente declaradas en el código, y las relaciones
apuntan de hijo a padre. Corregilo hasta que sea así.

RESPUESTA
Devolvé ÚNICAMENTE el contenido final del script, sin explicaciones y sin
envolverlo en bloques de markdown. La primera línea debe ser un shebang.`;
}

export interface GenerateOptions {
  /** Repo root the agent inspects (the task's worktree). */
  cwd: string;
  /** Display name, for the prompt. */
  repoName: string;
  /** Command to invoke the agent (config.defaultAgentCommand). */
  agentCommand: string;
  /** Optional model override. */
  model?: string;
}

export interface GenerateResult {
  script: string;
  /** stderr from the agent, useful when it went wrong. */
  log: string;
}

/**
 * Ask a Claude Code agent to write the extractor for this repo. Runs in print
 * mode with READ-ONLY tools: the agent inspects the code and returns the script
 * as text; writing it to disk is this server's job, not the agent's.
 */
export async function generateScript(
  opts: GenerateOptions,
): Promise<GenerateResult> {
  let stdout: string;
  let stderr = "";
  try {
    const res = await execFileAsync(opts.agentCommand, agentArgs(opts), {
      cwd: opts.cwd,
      timeout: GENERATE_TIMEOUT_MS,
      maxBuffer: MAX_OUTPUT_BYTES,
    });
    stdout = res.stdout;
    stderr = res.stderr;
  } catch (err) {
    throw agentFailure(err, opts.agentCommand);
  }

  const script = stripFences(stdout);
  if (!script.trim()) {
    throw new SchemaScriptError("El agente no devolvió ningún script.");
  }
  return { script, log: stderr };
}

/** Cómo se invoca al agente: print mode, herramientas de SÓLO LECTURA, texto plano. */
function agentArgs(opts: GenerateOptions): string[] {
  const args = [
    "-p",
    buildGenerationPrompt(opts.repoName),
    "--allowedTools",
    "Read",
    "Glob",
    "Grep",
    "Bash",
    "--permission-mode",
    "acceptEdits",
    "--output-format",
    "text",
  ];
  if (opts.model) args.push("--model", opts.model);
  return args;
}

/**
 * Traduce el fallo del agente al mensaje que va a leer el usuario en el panel.
 * Los dos modos que se distinguen —comando inexistente y corte por timeout— no
 * dejan stderr útil, así que sin este nombre propio se verían como "el agente
 * falló: " y nada más.
 */
function agentFailure(err: unknown, agentCommand: string): SchemaScriptError {
  const e = err as NodeJS.ErrnoException & { stderr?: string; killed?: boolean };
  if (e.code === "ENOENT") {
    return new SchemaScriptError(
      `No se encontró el comando \`${agentCommand}\` para generar el script.`,
    );
  }
  if (e.killed) {
    return new SchemaScriptError(
      `El agente superó los ${GENERATE_TIMEOUT_MS / 60_000} minutos y fue interrumpido.`,
    );
  }
  return new SchemaScriptError(
    `El agente falló: ${(e.stderr ?? e.message ?? "").trim().slice(0, 400)}`,
  );
}

/**
 * Agents are asked for a bare script, but a fenced block is the most likely
 * deviation, so unwrap it rather than writing an unrunnable file.
 */
export function stripFences(text: string): string {
  const trimmed = text.trim();
  const fenced = /^```[a-zA-Z]*\n([\s\S]*?)\n?```$/.exec(trimmed);
  return (fenced ? fenced[1] : trimmed).trim() + "\n";
}

/** Write the script + its metadata, making it executable. */
export async function saveScript(opts: {
  dataDir: string;
  projectRepoId: string;
  script: string;
  summary: string;
  now: string;
}): Promise<string> {
  const file = scriptPathFor(opts.dataDir, opts.projectRepoId);
  await fs.mkdir(path.dirname(file), { recursive: true });
  await fs.writeFile(file, opts.script, { mode: 0o755 });
  await fs.writeFile(
    metaPathFor(opts.dataDir, opts.projectRepoId),
    JSON.stringify({ generatedAt: opts.now, summary: opts.summary }, null, 2),
  );
  return file;
}

/** Delete a repo's script and metadata (idempotent). */
export async function deleteScript(
  dataDir: string,
  projectRepoId: string,
): Promise<void> {
  await fs.rm(scriptPathFor(dataDir, projectRepoId), { force: true });
  await fs.rm(metaPathFor(dataDir, projectRepoId), { force: true });
}

/** Assemble the graph a repo's script produced. */
export function toGraph(repoName: string, result: ExtractResult): SchemaGraph {
  return {
    repoName,
    dialect: result.dialect,
    sourceFiles: [
      ...new Set(
        [...result.entities, ...result.relations]
          .map((x) => x.sourceFile)
          .filter((f): f is string => typeof f === "string" && f.length > 0),
      ),
    ].sort(),
    entities: [...result.entities].sort((a, b) => a.name.localeCompare(b.name)),
    relations: [...result.relations].sort(
      (a, b) => a.from.localeCompare(b.from) || a.fromField.localeCompare(b.fromField),
    ),
  };
}

/* ── tiny guards ──────────────────────────────────────────────────────── */

function isRecord(v: unknown): v is Record<string, unknown> {
  return typeof v === "object" && v !== null && !Array.isArray(v);
}

function asString(v: unknown): string | null {
  return typeof v === "string" ? v : null;
}

function asPositiveInt(v: unknown): number | null {
  return typeof v === "number" && Number.isInteger(v) && v >= 0 ? v : null;
}
